workspace:
  base: /go
  path: src/forum

pipeline:
  test:
    image: golang:1.9-alpine
    commands:
      - go test -cover -coverpkg=./... -covermode=count ./tests

services:
  postgres:
    image: mongo:3.6