workspace:
  base: /go
  path: src/forum

pipeline:
  test:
    image: golang:1.9-alpine
    commands:
      - sleep 5
      - go test -cover -coverpkg=./... -covermode=count ./tests

services:
  forum-db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=forum
      - POSTGRES_PASSWORD=TSxdMxWB21Bt4j36
