workspace:
  base: /go
  path: src/forum

pipeline:
  test:
    image: golang:1.9
    commands:
      - sleep 5
      - go test -race -cover -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./tests
  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.out

services:
  forum-db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=TSxdMxWB21Bt4j36
