language: go
sudo: false
go:
  - 1.9.x
  - master

services:
  - mongodb

install: true

go_import_path: forum

script:
  - go test -cover -coverpkg=./... -covermode=count -coverprofile=coverage.out ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
